version: "2"

services:
  db:
    image: mariadb:10.4
    container_name: db
    environment:
      - MARIADB_ROOT_PASSWORD=uTk79mgR6Up2
      - MARIADB_USER=moodle-user
      - MARIADB_PASSWORD=H463XYPpU0GG
      - MARIADB_DATABASE=moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - moodle_docker_default

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      db:
        condition: service_started
    ports:
      - 7777:8080
    networks:
      - moodle_docker_default

  php:
    build:
      context: PHP/
      dockerfile: PHP.Dockerfile
    restart: always
    container_name: php
    volumes:
       - ./moodle:/var/www/html
       - ./moodledata:/var/www/moodledata
       - ./conf/local.ini:/usr/local/etc/php/php.ini
    networks:
      - moodle_docker_default
    depends_on:
      - db

  web:
    image: nginx
    restart: always
    container_name: web
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
     - php
    ports:
      - "8088:8088"
    networks:
      - moodle_docker_default

networks:
  traefik-global-proxy:
      external: true
  moodle_docker_default:
      external: false